DELETE http://localhost:3001/api/persons/6094190888412c0e04c6c837

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name":"hummer",
    "number":"010-123756"
}

###

GET http://localhost:3001/api/persons/6094191e8712fa0784821bdf

###

PUT http://localhost:3001/api/persons/6094191e8712fa0784821bdf
Content-Type: application/json

{
    "name":"mike",
    "number":"010-9888"
}