DELETE http://localhost:3001/api/persons/6094190888412c0e04c6c837

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name":"bigmo",
    "number":"010-123456"
}

###

GET http://localhost:3001/api/persons/6093faacc07c6c1554f06